import React,{useCallback,useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import './styles.css';
import {UNIVERSE} from './universe';
import {defaultAccount} from './paper';

type Candidate={symbol:string;segment:string;gapPct:number;activity:number;cprWidthPct:number;bias:'BULL'|'BEAR'|'NEUTRAL';score:number};

type ApiResult={source:string;status:string;asOf:string;candidates:Candidate[]};

function App(){
 const [candidates,setCandidates]=useState<Candidate[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState(false); const account=defaultAccount();
 const refresh=useCallback(async()=>{setLoading(true);setError(false);try{const r=await fetch('/api/screener',{cache:'no-store'});if(!r.ok)throw new Error('feed');const data:ApiResult=await r.json();setCandidates(data.candidates)}catch{setError(true)}finally{setLoading(false)}},[]);
 useEffect(()=>{refresh()},[refresh]);
 return <main className="app"><header><div><span className="eyebrow">NSE • INTRADAY INTELLIGENCE</span><h1>CPR Momentum <span>Screener</span></h1><p>Pre-market selection → structure → risk → paper-live.</p></div><div className="status"><i/> DEMO API • PAPER-LIVE READY</div></header><section className="hero"><div><label>SESSION</label><strong>Pre-Market</strong><small>Next scan window · 09:08 IST</small></div><div><label>UNIVERSE</label><strong>NIFTY 50 + NEXT 50</strong><small>{UNIVERSE.length} instruments loaded</small></div><div><label>ACCOUNT</label><strong>₹{account.equity.toLocaleString('en-IN')}</strong><small>Max risk ₹{account.maxRisk.toLocaleString('en-IN')} / trade</small></div><button onClick={refresh} disabled={loading}>{loading?'Refreshing…':'Refresh Screener ↻'}</button></section><nav><button className="active">Screener</button><button>Paper-Live</button><button>Daily Results</button><button>Risk Journal</button></nav><section className="content"><div className="panel"><div className="panelhead"><div><span className="eyebrow">RANKED SETUPS</span><h2>Morning Opportunities</h2></div><div className="filters"><span>Gap ≥ 1%</span><span>Activity ≥ 500k</span><span>CPR ≤ 0.5%</span></div></div>{error?<div className="guard">Screener API unavailable. No live order is permitted.</div>:<div className="table"><div className="thead"><span>SYMBOL</span><span>GAP</span><span>ACTIVITY</span><span>CPR WIDTH</span><span>BIAS</span><span>SCORE</span></div>{loading?<div className="row"><span>Loading market snapshot…</span></div>:candidates.slice(0,8).map(c=><div className="row" key={c.symbol}><strong>{c.symbol}</strong><span className={c.gapPct>0?'up':'down'}>{c.gapPct.toFixed(2)}%</span><span>{(c.activity/1000).toFixed(0)}k</span><span>{c.cprWidthPct.toFixed(2)}%</span><span className={c.bias==='BULL'?'bull':'bear'}>{c.bias}</span><b>{c.score}</b></div>)}</div>}</div><aside><div className="panel"><span className="eyebrow">RISK CONTROL</span><h2>Capital Guard</h2><div className="metric"><span>Demo equity</span><b>₹3,500</b></div><div className="metric"><span>Max risk / trade</span><b>₹700</b></div><div className="metric"><span>Execution</span><b>Paper-Live</b></div><div className="guard">Real-money orders are disabled.</div></div><div className="panel feed"><span className="eyebrow">DATA FEED</span><h2>Connection</h2><div><i/> DEMO API <small>server endpoint + freshness guard</small></div></div></aside></section><footer>Strategy engine: CPR · FVG · Order Block · Liquidity &nbsp;|&nbsp; No real-money execution enabled</footer></main>}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
