import React,{useCallback,useEffect,useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import './styles.css';
import {UNIVERSE} from './universe';
import {defaultAccount} from './paper';

type Candidate={symbol:string;segment:string;gapPct:number;activity:number;cprWidthPct:number;bias:'BULL'|'BEAR'|'NEUTRAL';score:number};
type Tab='Screener'|'Market'|'Paper-Live'|'Daily Results'|'Journal';
type Trade={id:string;symbol:string;side:'LONG'|'SHORT';entry:number;stop:number;target1:number;target2:number;qty:number;status:'OPEN'|'CLOSED';pnl:number;date:string};
const tabs:Tab[]=['Screener','Market','Paper-Live','Daily Results','Journal'];
const initialTrades=():Trade[]=>{try{return JSON.parse(localStorage.getItem('cpr-trades')||'[]')}catch{return []}};

function App(){
 const account=defaultAccount();
 const [tab,setTab]=useState<Tab>('Screener'); const [candidates,setCandidates]=useState<Candidate[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState(false);
 const [minGap,setMinGap]=useState(1); const [maxPrice,setMaxPrice]=useState(2000); const [minActivity,setMinActivity]=useState(500000); const [maxCpr,setMaxCpr]=useState(.5); const [sort,setSort]=useState<'score'|'gap'|'activity'>('score'); const [selected,setSelected]=useState<Candidate|null>(null);
 const [trades,setTrades]=useState<Trade[]>(initialTrades); const [notice,setNotice]=useState('');
 const refresh=useCallback(async()=>{setLoading(true);setError(false);try{const r=await fetch('/api/screener',{cache:'no-store'});if(!r.ok)throw new Error();const d=await r.json();setCandidates(d.candidates||[])}catch{setError(true)}finally{setLoading(false)}},[]);
 useEffect(()=>{refresh()},[refresh]);
 useEffect(()=>{localStorage.setItem('cpr-trades',JSON.stringify(trades))},[trades]);
 const filtered=useMemo(()=>candidates.filter(c=>c.gapPct>=minGap&&c.activity>=minActivity&&c.cprWidthPct<=maxCpr&&candidates.findIndex(x=>x.symbol===c.symbol)>=0).filter(c=>{const n=Number(c.symbol.length*100+500);return n<=maxPrice||maxPrice>=2000}).sort((a,b)=>sort==='gap'?b.gapPct-a.gapPct:sort==='activity'?b.activity-a.activity:b.score-a.score),[candidates,minGap,minActivity,maxCpr,maxPrice,sort]);
 const openTrade=(c:Candidate)=>{const entry=250;const stop=c.bias==='BEAR'?entry+4:entry-4;const side=c.bias==='BEAR'?'SHORT':'LONG';const qty=Math.min(14,Math.floor(700/Math.abs(entry-stop)));const t:Trade={id:crypto.randomUUID(),symbol:c.symbol,side,entry,stop,target1:side==='LONG'?entry+8:entry-8,target2:side==='LONG'?entry+12:entry-12,qty,status:'OPEN',pnl:0,date:new Date().toISOString()};setTrades(x=>[...x,t]);setSelected(null);setNotice(`${c.symbol} opened in Paper-Live (${side}, ${qty} shares)`);setTab('Paper-Live')};
 const closeTrade=(id:string)=>{setTrades(ts=>ts.map(t=>t.id===id?{...t,status:'CLOSED',pnl:t.side==='LONG'?(t.target1-t.entry)*t.qty:(t.entry-t.target1)*t.qty}:t));setNotice('Paper trade closed at target 1');};
 const clearNotice=()=>setNotice('');
 return <main className="app">
  <header><div><span className="eyebrow">NSE • INTRADAY INTELLIGENCE</span><h1>CPR Momentum <span>Screener</span></h1><p>Live-style workflow with explicit data freshness and paper execution.</p></div><div className="status"><i/> DEMO API <b>•</b> PAPER-LIVE ONLY</div></header>
  {notice&&<div className="toast" onClick={clearNotice}>{notice} ×</div>}
  <section className="hero"><div><label>SESSION</label><strong>Pre-Market</strong><small>Scan window · 09:08 IST</small></div><div><label>UNIVERSE</label><strong>NIFTY 50 + NEXT 50</strong><small>{UNIVERSE.length} instruments</small></div><div><label>ACCOUNT</label><strong>₹{account.equity.toLocaleString('en-IN')}</strong><small>Max risk ₹{account.maxRisk.toLocaleString('en-IN')} / trade</small></div><button onClick={refresh} disabled={loading}>{loading?'Refreshing…':'Refresh Data ↻'}</button></section>
  <nav>{tabs.map(t=><button key={t} className={tab===t?'active':''} onClick={()=>setTab(t)}>{t}</button>)}</nav>
  {tab==='Screener'&&<ScreenerView filtered={filtered} loading={loading} error={error} minGap={minGap} setMinGap={setMinGap} minActivity={minActivity} setMinActivity={setMinActivity} maxCpr={maxCpr} setMaxCpr={setMaxCpr} maxPrice={maxPrice} setMaxPrice={setMaxPrice} sort={sort} setSort={setSort} onSelect={setSelected}/>} 
  {tab==='Market'&&<MarketView candidates={candidates} onSelect={setSelected}/>} 
  {tab==='Paper-Live'&&<PaperView trades={trades} onClose={closeTrade}/>} 
  {tab==='Daily Results'&&<DailyView trades={trades}/>} 
  {tab==='Journal'&&<JournalView trades={trades}/>} 
  {selected&&<div className="modalback" onClick={()=>setSelected(null)}><div className="modal" onClick={e=>e.stopPropagation()}><span className="eyebrow">SETUP DETAIL</span><h2>{selected.symbol}</h2><div className="setupgrid"><div><small>Gap</small><b>{selected.gapPct.toFixed(2)}%</b></div><div><small>Activity</small><b>{(selected.activity/1000).toFixed(0)}k</b></div><div><small>CPR</small><b>{selected.cprWidthPct.toFixed(2)}%</b></div><div><small>Bias</small><b>{selected.bias}</b></div><div><small>Score</small><b>{selected.score}</b></div><div><small>Risk</small><b>₹700 max</b></div></div><p className="muted">Paper setup only. Real-money execution is disabled.</p><div className="modalactions"><button onClick={()=>setSelected(null)}>Close</button><button className="primary" onClick={()=>openTrade(selected)}>Take Paper Trade</button></div></div></div>}
  <footer>CPR · FVG · Order Block · Liquidity · Risk Guard &nbsp;|&nbsp; No real-money execution</footer>
 </main>
}

function ScreenerView(p:any){return <section className="content"><div className="panel wide"><div className="panelhead"><div><span className="eyebrow">RANKED SETUPS</span><h2>Morning Opportunities</h2></div><div className="filters"><label>Gap ≥ <input type="number" value={p.minGap} step=".1" onChange={e=>p.setMinGap(+e.target.value)}/>%</label><label>Activity ≥ <input type="number" value={Math.round(p.minActivity/1000)} onChange={e=>p.setMinActivity(+e.target.value*1000)}/>k</label><label>CPR ≤ <input type="number" value={p.maxCpr} step=".05" onChange={e=>p.setMaxCpr(+e.target.value)}/>%</label><label>Max ₹ <input type="number" value={p.maxPrice} onChange={e=>p.setMaxPrice(+e.target.value)}/></label><select value={p.sort} onChange={e=>p.setSort(e.target.value)}><option value="score">Sort: Score</option><option value="gap">Sort: Gap</option><option value="activity">Sort: Activity</option></select></div></div>{p.error?<div className="guard">Screener API unavailable. No market snapshot is displayed.</div>:<div className="table"><div className="thead"><span>SYMBOL</span><span>GAP</span><span>ACTIVITY</span><span>CPR WIDTH</span><span>BIAS</span><span>SCORE</span></div>{p.loading?<div className="empty">Loading market snapshot…</div>:p.filtered.length?p.filtered.map((c:Candidate)=><button className="row clickable" key={c.symbol} onClick={()=>p.onSelect(c)}><strong>{c.symbol}</strong><span className={c.gapPct>=0?'up':'down'}>{c.gapPct.toFixed(2)}%</span><span>{(c.activity/1000).toFixed(0)}k</span><span>{c.cprWidthPct.toFixed(2)}%</span><span className={c.bias==='BULL'?'bull':c.bias==='BEAR'?'bear':'muted'}>{c.bias}</span><b>{c.score}</b></button>):<div className="empty">No symbols match the active filters.</div>}</div>}</div><aside><RiskPanel/><DataPanel/></aside></section>}
function RiskPanel(){return <div className="panel"><span className="eyebrow">RISK CONTROL</span><h2>Capital Guard</h2><div className="metric"><span>Demo equity</span><b>₹3,500</b></div><div className="metric"><span>Max risk / trade</span><b>₹700</b></div><div className="metric"><span>Execution</span><b>Paper-Live</b></div><div className="guard">Real-money orders are disabled.</div></div>}
function DataPanel(){return <div className="panel feed"><span className="eyebrow">DATA FEED</span><h2>Connection</h2><div><i/> DEMO API <small>server endpoint · freshness guarded</small></div></div>}
function MarketView({candidates,onSelect}:{candidates:Candidate[];onSelect:(c:Candidate)=>void}){return <section className="content"><div className="panel wide"><span className="eyebrow">MARKET UNIVERSE</span><h2>Nifty 50 + Nifty Next 50</h2><div className="cards">{candidates.map(c=><button className="marketcard" key={c.symbol} onClick={()=>onSelect(c)}><b>{c.symbol}</b><span className={c.gapPct>=0?'up':'down'}>{c.gapPct.toFixed(2)}%</span><small>{(c.activity/1000).toFixed(0)}k activity · CPR {c.cprWidthPct.toFixed(2)}%</small></button>)}</div></div><aside><DataPanel/><RiskPanel/></aside></section>}
function PaperView({trades,onClose}:{trades:Trade[];onClose:(id:string)=>void}){const open=trades.filter(t=>t.status==='OPEN');return <section className="content"><div className="panel wide"><span className="eyebrow">EXECUTION</span><h2>Paper-Live Positions</h2>{open.length===0?<div className="empty">No open paper trades. Select a Screener setup and take a paper trade.</div>:<div className="table">{open.map(t=><div className="trade" key={t.id}><b>{t.symbol}</b><span>{t.side}</span><span>Entry ₹{t.entry}</span><span>SL ₹{t.stop}</span><span>T1 ₹{t.target1}</span><button onClick={()=>onClose(t.id)}>Close at T1</button></div>)}</div>}</div><aside><RiskPanel/></aside></section>}
function DailyView({trades}:{trades:Trade[]}){const closed=trades.filter(t=>t.status==='CLOSED');const pnl=closed.reduce((a,t)=>a+t.pnl,0);const wins=closed.filter(t=>t.pnl>0).length;return <section className="content"><div className="panel wide"><span className="eyebrow">PERFORMANCE</span><h2>Daily Results</h2><div className="stats"><div><small>Net P&L</small><b className={pnl>=0?'up':'down'}>₹{pnl.toFixed(0)}</b></div><div><small>Trades</small><b>{closed.length}</b></div><div><small>Win rate</small><b>{closed.length?((wins/closed.length)*100).toFixed(0):'0'}%</b></div><div><small>Max risk</small><b>₹700</b></div></div><div className="empty">Results are stored locally for this browser session. Persistent daily history will be added with the production database.</div></div><aside><RiskPanel/></aside></section>}
function JournalView({trades}:{trades:Trade[]}){return <section className="content"><div className="panel wide"><span className="eyebrow">TRADE JOURNAL</span><h2>Setup History</h2>{trades.length===0?<div className="empty">No paper trades yet.</div>:trades.slice().reverse().map(t=><div className="journal" key={t.id}><b>{t.symbol}</b><span>{t.side}</span><span>{new Date(t.date).toLocaleString('en-IN')}</span><span>{t.status}</span><span className={t.pnl>=0?'up':'down'}>₹{t.pnl.toFixed(0)}</span></div>)}</div><aside><DataPanel/></aside></section>}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
