import React,{useCallback,useEffect,useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import './styles.css';
import {UNIVERSE} from './universe';
import {defaultAccount} from './paper';

type Candidate={symbol:string;segment:string;gapPct:number;activity:number;cprWidthPct:number;bias:'BULL'|'BEAR'|'NEUTRAL';score:number;price?:number|null;prevClose?:number|null};
type Tab='Live Screener'|'Market'|'Trader'|'Paper-Live'|'Daily Results'|'Risk Journal'|'Data';
type Trade={id:string;symbol:string;side:'LONG'|'SHORT';entry:number;stop:number;target1:number;target2:number;qty:number;status:'OPEN'|'CLOSED';pnl:number;date:string};
const tabs:Tab[]=['Live Screener','Market','Trader','Paper-Live','Daily Results','Risk Journal','Data'];
const tabHash=(t:Tab)=>t.toLowerCase().replaceAll(' ','-');
const hashTab=():Tab=>{const h=location.hash.replace('#/','');const found=tabs.find(t=>tabHash(t)===h);return found||'Live Screener'};
const initialTrades=():Trade[]=>{try{return JSON.parse(localStorage.getItem('cpr-trades')||'[]')}catch{return []}};

function App(){
 const account=defaultAccount();
 const [tab,setTab]=useState<Tab>(hashTab());
 const [candidates,setCandidates]=useState<Candidate[]>([]);
 const [loading,setLoading]=useState(true); const [error,setError]=useState(false);
 const [feed,setFeed]=useState({source:'UNKNOWN',status:'UNKNOWN',asOf:''});
 const [minGap,setMinGap]=useState(1); const [maxPrice,setMaxPrice]=useState(2000); const [minActivity,setMinActivity]=useState(500000); const [maxCpr,setMaxCpr]=useState(.5); const [sort,setSort]=useState<'score'|'gap'|'activity'>('score');
 const [selected,setSelected]=useState<Candidate|null>(null); const [traderSymbol,setTraderSymbol]=useState<Candidate|null>(null); const [trades,setTrades]=useState<Trade[]>(initialTrades); const [notice,setNotice]=useState('');
 const navigate=useCallback((next:Tab)=>{setTab(next);location.hash=`/${tabHash(next)}`},[]);
 useEffect(()=>{const onHash=()=>setTab(hashTab());addEventListener('hashchange',onHash);if(!location.hash)location.hash='/live-screener';return()=>removeEventListener('hashchange',onHash)},[]);
 const refresh=useCallback(async()=>{setLoading(true);setError(false);try{const r=await fetch('/api/screener',{cache:'no-store'});if(!r.ok)throw new Error();const d=await r.json();setCandidates(d.candidates||[]);setFeed({source:d.source||'UNKNOWN',status:d.status||'UNKNOWN',asOf:d.asOf||''})}catch{setError(true);setFeed({source:'UNAVAILABLE',status:'ERROR',asOf:''})}finally{setLoading(false)}},[]);
 useEffect(()=>{refresh()},[refresh]); useEffect(()=>{localStorage.setItem('cpr-trades',JSON.stringify(trades))},[trades]);
 const filtered=useMemo(()=>candidates.filter(c=>c.gapPct>=minGap&&c.activity>=minActivity&&c.cprWidthPct<=maxCpr&&(c.price==null||c.price<=maxPrice)).sort((a,b)=>sort==='gap'?b.gapPct-a.gapPct:sort==='activity'?b.activity-a.activity:b.score-a.score),[candidates,minGap,minActivity,maxCpr,maxPrice,sort]);
 const openTrader=(c:Candidate)=>{setTraderSymbol(c);navigate('Trader')};
 const openTrade=(c:Candidate,custom?:{entry:number;stop:number;target1:number;target2:number;qty:number})=>{const entry=custom?.entry??(c.price&&c.price>0?c.price:250);const stop=custom?.stop??(c.bias==='BEAR'?entry+4:entry-4);const side:candidateSide=c.bias==='BEAR'?'SHORT':'LONG';const risk=Math.abs(entry-stop);const qty=custom?.qty??Math.min(14,Math.floor(account.maxRisk/risk));if(qty<1){setNotice('Risk guard blocked this setup: quantity must be at least 1.');return}const t:Trade={id:crypto.randomUUID(),symbol:c.symbol,side,entry,stop,target1:custom?.target1??(side==='LONG'?entry+8:entry-8),target2:custom?.target2??(side==='LONG'?entry+12:entry-12),qty,status:'OPEN',pnl:0,date:new Date().toISOString()};setTrades(x=>[...x,t]);setTraderSymbol(null);setSelected(null);setNotice(`${c.symbol} paper order opened (${side}, ${qty} shares)`);navigate('Paper-Live')};
 const closeTrade=(id:string)=>{setTrades(ts=>ts.map(t=>t.id===id?{...t,status:'CLOSED',pnl:t.side==='LONG'?(t.target1-t.entry)*t.qty:(t.entry-t.target1)*t.qty}:t));setNotice('Paper trade closed at T1');};
 const selectedOrFirst=traderSymbol||candidates[0]||null;
 return <main className="app"><header><div><span className="eyebrow">NSE • INTRADAY INTELLIGENCE</span><h1>CPR Momentum <span>Screener</span></h1><p>Live-market architecture with explicit feed status and paper execution.</p></div><div className={`status ${feed.status==='LIVE'?'live':''}`}><i/> {feed.status==='LIVE'?'LIVE FEED':'DEMO / NOT LIVE'} <b>•</b> PAPER-LIVE ONLY</div></header>
 {notice&&<div className="toast" onClick={()=>setNotice('')}>{notice} ×</div>}
 <section className="hero"><div><label>SESSION</label><strong>Pre-Market</strong><small>Scan window · 09:08 IST</small></div><div><label>UNIVERSE</label><strong>NIFTY 50 + NEXT 50</strong><small>{UNIVERSE.length} instruments</small></div><div><label>ACCOUNT</label><strong>₹{account.equity.toLocaleString('en-IN')}</strong><small>Max risk ₹{account.maxRisk.toLocaleString('en-IN')} / trade</small></div><button onClick={refresh} disabled={loading}>{loading?'Refreshing…':'Refresh Market Data ↻'}</button></section>
 <nav aria-label="Primary navigation">{tabs.map(t=><button key={t} className={tab===t?'active':''} onClick={()=>navigate(t)}>{t}</button>)}</nav>
 {tab==='Live Screener'&&<ScreenerView filtered={filtered} loading={loading} error={error} feed={feed} minGap={minGap} setMinGap={setMinGap} minActivity={minActivity} setMinActivity={setMinActivity} maxCpr={maxCpr} setMaxCpr={setMaxCpr} maxPrice={maxPrice} setMaxPrice={setMaxPrice} sort={sort} setSort={setSort} onSelect={setSelected} onTrader={openTrader}/>} 
 {tab==='Market'&&<MarketView candidates={candidates} onSelect={setSelected} onTrader={openTrader}/>} 
 {tab==='Trader'&&<TraderView candidate={selectedOrFirst} candidates={candidates} onSelect={setTraderSymbol} onPlace={openTrade} feed={feed}/>} 
 {tab==='Paper-Live'&&<PaperView trades={trades} onClose={closeTrade}/>} 
 {tab==='Daily Results'&&<DailyView trades={trades}/>} 
 {tab==='Risk Journal'&&<JournalView trades={trades}/>} 
 {tab==='Data'&&<DataView feed={feed} candidates={candidates} onRefresh={refresh}/>} 
 {selected&&<div className="modalback" onClick={()=>setSelected(null)}><div className="modal" onClick={e=>e.stopPropagation()}><span className="eyebrow">SETUP DETAIL</span><h2>{selected.symbol}</h2><div className="setupgrid"><div><small>Price</small><b>{selected.price!=null?`₹${selected.price.toFixed(2)}`:'—'}</b></div><div><small>Gap</small><b>{selected.gapPct.toFixed(2)}%</b></div><div><small>Activity</small><b>{(selected.activity/1000).toFixed(0)}k</b></div><div><small>CPR</small><b>{selected.cprWidthPct.toFixed(2)}%</b></div><div><small>Bias</small><b>{selected.bias}</b></div><div><small>Score</small><b>{selected.score}</b></div></div><p className="muted">{feed.status==='LIVE'?'Live market snapshot.':'Demo market snapshot.'} Real-money execution is disabled.</p><div className="modalactions"><button onClick={()=>setSelected(null)}>Close</button><button className="primary" onClick={()=>openTrader(selected)}>Open Trader</button></div></div></div>}
 <footer>CPR · FVG · Order Block · Liquidity · Risk Guard &nbsp;|&nbsp; Real-money execution disabled</footer></main>}
type candidateSide='LONG'|'SHORT';
function RiskPanel(){return <div className="panel"><span className="eyebrow">RISK CONTROL</span><h2>Capital Guard</h2><div className="metric"><span>Demo equity</span><b>₹3,500</b></div><div className="metric"><span>Max risk / trade</span><b>₹700</b></div><div className="metric"><span>Execution</span><b>Paper-Live</b></div><div className="guard">Real-money orders are disabled.</div></div>}
function DataPanel({feed}:{feed?:{source:string;status:string;asOf:string}}){const f=feed||{source:'DEMO',status:'DEMO',asOf:''};return <div className="panel feed"><span className="eyebrow">DATA FEED</span><h2>Connection</h2><div><i className={f.status==='LIVE'?'live-dot':''}/> {f.status==='LIVE'?'LIVE':'DEMO'} ADAPTER <small>{f.source} {f.asOf?`· ${new Date(f.asOf).toLocaleTimeString('en-IN')}`:''}</small></div></div>}
function ScreenerView(p:any){return <section className="content"><div className="panel wide"><div className="panelhead"><div><span className="eyebrow">LIVE SCREENER WORKSPACE</span><h2>Morning Opportunities</h2></div><div className="filters"><label>Gap ≥ <input type="number" value={p.minGap} step=".1" onChange={e=>p.setMinGap(+e.target.value)}/>%</label><label>Activity ≥ <input type="number" value={Math.round(p.minActivity/1000)} onChange={e=>p.setMinActivity(+e.target.value*1000)}/>k</label><label>CPR ≤ <input type="number" value={p.maxCpr} step=".05" onChange={e=>p.setMaxCpr(+e.target.value)}/>%</label><label>Max ₹ <input type="number" value={p.maxPrice} onChange={e=>p.setMaxPrice(+e.target.value)}/></label><select value={p.sort} onChange={e=>p.setSort(e.target.value)}><option value="score">Sort: Score</option><option value="gap">Sort: Gap</option><option value="activity">Sort: Activity</option></select></div></div>{p.error?<div className="guard">Market API unavailable. No stale snapshot is displayed.</div>:<><div className="table"><div className="thead"><span>SYMBOL</span><span>GAP</span><span>ACTIVITY</span><span>CPR WIDTH</span><span>BIAS</span><span>SCORE</span></div>{p.loading?<div className="empty">Loading market snapshot…</div>:p.filtered.length?p.filtered.map((c:Candidate)=><button className="row clickable" key={c.symbol} onClick={()=>p.onSelect(c)}><strong>{c.symbol}</strong><span className={c.gapPct>=0?'up':'down'}>{c.gapPct.toFixed(2)}%</span><span>{(c.activity/1000).toFixed(0)}k</span><span>{c.cprWidthPct.toFixed(2)}%</span><span className={c.bias==='BULL'?'bull':c.bias==='BEAR'?'bear':'muted'}>{c.bias}</span><b>{c.score}</b></button>):<div className="empty">No symbols match the active filters.</div>}</div><div className="table-actions"><button onClick={()=>p.onTrader(p.filtered[0])} disabled={!p.filtered.length}>Trade top setup →</button><span>{p.feed.status==='LIVE'?'LIVE DATA':'DEMO DATA'} · {p.feed.asOf?new Date(p.feed.asOf).toLocaleTimeString('en-IN'):'not timestamped'}</span></div></>}</div><aside><RiskPanel/><DataPanel feed={p.feed}/></aside></section>}
function MarketView({candidates,onSelect,onTrader}:{candidates:Candidate[];onSelect:(c:Candidate)=>void;onTrader:(c:Candidate)=>void}){return <section className="content"><div className="panel wide"><span className="eyebrow">MARKET UNIVERSE</span><h2>Nifty 50 + Nifty Next 50</h2><div className="cards">{candidates.map(c=><div className="marketcard" key={c.symbol}><button onClick={()=>onSelect(c)}><b>{c.symbol}</b><span className={c.gapPct>=0?'up':'down'}>{c.gapPct.toFixed(2)}%</span><small>{c.price!=null?`₹${c.price.toFixed(2)} · `:''}{(c.activity/1000).toFixed(0)}k activity · CPR {c.cprWidthPct.toFixed(2)}%</small></button><button className="mini" onClick={()=>onTrader(c)}>Trader</button></div>)}</div></div><aside><DataPanel/><RiskPanel/></aside></section>}
function TraderView({candidate,candidates,onSelect,onPlace,feed}:{candidate:Candidate|null;candidates:Candidate[];onSelect:(c:Candidate)=>void;onPlace:(c:Candidate,custom:{entry:number;stop:number;target1:number;target2:number;qty:number})=>void;feed:any}){const [entry,setEntry]=useState(candidate?.price||0);const [stop,setStop]=useState(0);const [t1,setT1]=useState(0);const [t2,setT2]=useState(0);const [qty,setQty]=useState(1);useEffect(()=>{if(candidate){const e=candidate.price||250;const s=candidate.bias==='BEAR'?e+4:e-4;const side=candidate.bias==='BEAR'?'SHORT':'LONG';setEntry(e);setStop(s);setT1(side==='LONG'?e+8:e-8);setT2(side==='LONG'?e+12:e-12);setQty(Math.max(1,Math.min(14,Math.floor(700/Math.abs(e-s)))))}},[candidate]);const side=candidate?.bias==='BEAR'?'SHORT':'LONG';const risk=Math.abs(entry-stop)*qty;const rr=Math.abs(t1-entry)/(Math.abs(entry-stop)||1);return <section className="content"><div className="panel wide"><div className="trader-head"><div><span className="eyebrow">TRADER WORKSPACE</span><h2>Precision Paper Execution</h2></div><span className="mode">{feed.status==='LIVE'?'LIVE MARKET':'DEMO MARKET'}</span></div><div className="symbol-picker"><label>SYMBOL<select value={candidate?.symbol||''} onChange={e=>onSelect(candidates.find(c=>c.symbol===e.target.value)||null)}><option value="">Select a setup</option>{candidates.map(c=><option key={c.symbol} value={c.symbol}>{c.symbol}</option>)}</select></label></div>{candidate?<><div className="chart"><div className="chartline"/><div className="chartlabel">5m / 15m structure preview</div><div className="levels"><span>CPR {candidate.cprWidthPct.toFixed(2)}%</span><span>Bias {candidate.bias}</span><span>Score {candidate.score}</span></div></div><div className="order-grid"><label>ENTRY<input type="number" value={entry} onChange={e=>setEntry(+e.target.value)}/></label><label>STOP LOSS<input type="number" value={stop} onChange={e=>setStop(+e.target.value)}/></label><label>TARGET 1<input type="number" value={t1} onChange={e=>setT1(+e.target.value)}/></label><label>TARGET 2<input type="number" value={t2} onChange={e=>setT2(+e.target.value)}/></label><label>QTY<input type="number" min="1" value={qty} onChange={e=>setQty(Math.max(1,+e.target.value))}/></label></div><div className="trade-summary"><div><small>SIDE</small><b className={side==='LONG'?'bull':'bear'}>{side}</b></div><div><small>RISK</small><b>₹{risk.toFixed(0)}</b></div><div><small>R:R TO T1</small><b>{rr.toFixed(2)}R</b></div><div><small>MAX RISK</small><b>₹700</b></div></div><div className="modalactions"><button onClick={()=>{const s=candidate.bias==='BEAR'?(entry+4):(entry-4);setStop(s)}}>Reset SL</button><button className="primary" disabled={risk>700||qty<1} onClick={()=>onPlace(candidate,{entry,stop,target1:t1,target2:t2,qty})}>Place Paper Order</button></div></>:<div className="empty">Select a screened symbol to open the trader workspace.</div>}</div><aside><RiskPanel/><DataPanel feed={feed}/></aside></section>}
function PaperView({trades,onClose}:{trades:Trade[];onClose:(id:string)=>void}){const open=trades.filter(t=>t.status==='OPEN');return <section className="content"><div className="panel wide"><span className="eyebrow">EXECUTION</span><h2>Paper-Live Positions</h2>{open.length===0?<div className="empty">No open paper trades. Select a Screener setup and place a paper order.</div>:<div className="table">{open.map(t=><div className="trade" key={t.id}><b>{t.symbol}</b><span>{t.side}</span><span>Entry ₹{t.entry.toFixed(2)}</span><span>SL ₹{t.stop.toFixed(2)}</span><span>T1 ₹{t.target1.toFixed(2)}</span><button onClick={()=>onClose(t.id)}>Close at T1</button></div>)}</div>}</div><aside><RiskPanel/></aside></section>}
function DailyView({trades}:{trades:Trade[]}){const closed=trades.filter(t=>t.status==='CLOSED');const pnl=closed.reduce((a,t)=>a+t.pnl,0);const wins=closed.filter(t=>t.pnl>0).length;return <section className="content"><div className="panel wide"><span className="eyebrow">PERFORMANCE</span><h2>Daily Results</h2><div className="stats"><div><small>Net P&L</small><b className={pnl>=0?'up':'down'}>₹{pnl.toFixed(0)}</b></div><div><small>Trades</small><b>{closed.length}</b></div><div><small>Win rate</small><b>{closed.length?((wins/closed.length)*100).toFixed(0):'0'}%</b></div><div><small>Max risk</small><b>₹700</b></div></div><div className="empty">Paper results are persisted in this browser. Production persistence will be enabled with the database layer.</div></div><aside><RiskPanel/></aside></section>}
function JournalView({trades}:{trades:Trade[]}){return <section className="content"><div className="panel wide"><span className="eyebrow">RISK JOURNAL</span><h2>Trade History</h2>{trades.length===0?<div className="empty">No paper trades yet.</div>:trades.slice().reverse().map(t=><div className="journal" key={t.id}><b>{t.symbol}</b><span>{t.side}</span><span>{new Date(t.date).toLocaleString('en-IN')}</span><span>{t.status}</span><span className={t.pnl>=0?'up':'down'}>₹{t.pnl.toFixed(0)}</span></div>)}</div><aside><DataPanel/></aside></section>}
function DataView({feed,candidates,onRefresh}:{feed:any;candidates:Candidate[];onRefresh:()=>void}){return <section className="content"><div className="panel wide"><span className="eyebrow">MARKET DATA</span><h2>Feed Diagnostics</h2><div className="stats"><div><small>Source</small><b>{feed.source}</b></div><div><small>Status</small><b className={feed.status==='LIVE'?'up':'down'}>{feed.status}</b></div><div><small>Symbols</small><b>{candidates.length}</b></div><div><small>As Of</small><b>{feed.asOf?new Date(feed.asOf).toLocaleTimeString('en-IN'):'—'}</b></div></div><div className="guard">TradingView does not provide a general public market-data API. The application therefore does not scrape TradingView. A verified market-data/broker adapter must be configured before this can truthfully be called LIVE.</div><div className="modalactions"><button onClick={onRefresh}>Test feed now</button></div></div><aside><DataPanel feed={feed}/></aside></section>}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
